### ISSUE TITLE
Create gnomad-gks demo notebook for GA4GH connect workshop

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/gnomad-frequency-report#12]

**Comment by larrybabb** [comment]
@theferrit32 didn't you do this? If not, maybe we should close it and re-create if needed later.

**Comment by theferrit32** [comment]
I think this is done

https://github.com/ga4gh/va-spec/blob/1.0-alpha/notebooks/gnomad-v4-gks-v1.0-alpha.ipynb
