### ISSUE TITLE
Debug missing HGVS values in RUNX1, CDH1, and other genes

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/gnomad-frequency-report#8]
This is for [gnomad-clinvar-af-revstatus.ipynb](https://github.com/clingen-data-model/gnomad-frequency-report/blob/master/gnomad-clinvar-af-revstatus.ipynb)

Could be related to upgrade to gnomad v3, messing up the join between different dataframes.

**Comment by KelseaChang5** [comment]
December 7th 2021 Triage: Closed
